{% set name = "hdx-python-country" %}
{% set version = "3.6.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: c6902b435346037871a91315c03e28e87fb0d391cb36da70f49f6b9ee36b0731

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=3.8
    - hdx-python-utilities >=3.6.2
    - libhxl >=5.1
    - pyphonetics

test:
  imports:
    - hdx.location.adminlevel
    - hdx.location.country
    - hdx.location.currency
    - hdx.location.names
    - hdx.location.phonetics
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://hdx-python-country.readthedocs.io
  summary: |
    Utilities to map between country and region codes and names and to match
    administrative level names from different sources
  description: |
    The HDX Python Country Library provides utilities to map between country
    and region codes and names and to match administrative level names from
    different sources. It also provides utilities for foreign exchange enabling
    obtaining current and historic FX rates for different currencies.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://hdx-python-country.readthedocs.io
  dev_url: https://github.com/OCHA-DAP/hdx-python-country

extra:
  recipe-maintainers:
    - kynan
    - mcarans
