{% set name = "hdx-python-country" %}
{% set version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 0f47ec467d662a1903925ee7211adf2a1ba55d78a312f11227e4dd0857d95960

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - hdx-python-utilities >=4.0.0
    - libhxl >=5.2.2
    - tenacity

test:
  imports:
    - hdx.location.adminlevel
    - hdx.location.country
    - hdx.location.currency
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://hdx-python-country.readthedocs.io
  summary: |
    Utilities to map between country and region codes and names, and to match
    administrative level names from different sources
  description: |
    The HDX Python Country Library provides utilities to map between country
    and region codes and names and to match administrative level names from
    different sources. It also provides utilities for foreign exchange enabling
    obtaining current and historic FX rates for different currencies.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://hdx-python-country.readthedocs.io
  dev_url: https://github.com/OCHA-DAP/hdx-python-country

extra:
  recipe-maintainers:
    - kynan
    - mcarans
