{% set name = "hdx-python-country" %}
{% set version = "3.9.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: cf156f5c90e54e8f7336698085a9901a95ff08580418de330e94ca4923f4f3ef

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >={{ python_min }}
    - hdx-python-utilities >=3.8.5
    - libhxl >=5.2.2
    - tenacity

test:
  imports:
    - hdx.location.adminlevel
    - hdx.location.country
    - hdx.location.currency
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://hdx-python-country.readthedocs.io
  summary: |
    Utilities to map between country and region codes and names, and to match
    administrative level names from different sources
  description: |
    The HDX Python Country Library provides utilities to map between country
    and region codes and names and to match administrative level names from
    different sources. It also provides utilities for foreign exchange enabling
    obtaining current and historic FX rates for different currencies.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://hdx-python-country.readthedocs.io
  dev_url: https://github.com/OCHA-DAP/hdx-python-country

extra:
  recipe-maintainers:
    - kynan
    - mcarans
