{% set name = "hdx-python-country" %}
{% set version = "3.4.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 40e06bf1211e44cab568180f8998823cee3a48aa709995efa4860cb08cfd94f9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - hdx-python-utilities >=3.5.5
    - libhxl >=4.27.3
    - pyphonetics

test:
  imports:
    - hdx.location.adminlevel
    - hdx.location.country
    - hdx.location.currency
    - hdx.location.names
    - hdx.location.phonetics
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://hdx-python-country.readthedocs.io
  summary: |
    Utilities to map between country and region codes and names and to match
    administrative level names from different sources
  description: |
    The HDX Python Country Library provides utilities to map between country
    and region codes and names and to match administrative level names from
    different sources. It also provides utilities for foreign exchange enabling
    obtaining current and historic FX rates for different currencies.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://hdx-python-country.readthedocs.io
  dev_url: https://github.com/OCHA-DAP/hdx-python-country

extra:
  recipe-maintainers:
    - kynan
    - mcarans
